from sqlmodel import SQLModel, Field
from sqlalchemy import Column, JSON, UniqueConstraint, Index
from typing import Optional
from uuid import uuid4
from datetime import datetime


def _uuid() -> str:
    return str(uuid4())


def _now_iso() -> str:
    return datetime.utcnow().isoformat()


class User(SQLModel, table=True):
    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    linkedin_id: Optional[str] = None
    name: str
    avatar_url: Optional[str] = None
    career_tag: Optional[str] = None
    is_mentor: bool = False
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    # Backboard assistant = this user's persistent long-term speaking coach.
    # One per Heard user so coaching memories are never mixed between users.
    backboard_assistant_id: Optional[str] = None


class Speech(SQLModel, table=True):
    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    user_id: str = Field(foreign_key="user.id")
    status: str = "live"
    started_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    ended_at: Optional[str] = None
    # Backboard thread = this one practice/presentation session. Each 60s
    # RealtimeSegment becomes one message in this thread.
    backboard_thread_id: Optional[str] = None


class SpeechMetrics(SQLModel, table=True):
    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    speech_id: str = Field(foreign_key="speech.id")
    clarity: int = 0
    volume: int = 0
    pace: int = 0
    confidence: int = 0
    structure: int = 0
    overall: int = 0
    summary: str = ""
    suggestions: str = "[]"
    mentor_suggestions: str = "[]"


class RealtimeSegment(SQLModel, table=True):
    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    speech_id: str = Field(foreign_key="speech.id")
    transcript: str
    nudge: str = ""                         # short live recommendation shown in the sidebar
    segment_index: int
    recorded_at: str
    duration_seconds: float
    avg_volume: int = 0
    volume_variance: int = 0
    # Full structured coaching payload from Backboard/Gemini (focus_area,
    # evidence, progress, next_minute_goal, scores). Sidebar shows only `nudge`.
    feedback_json: str = "{}"


class CommunityPost(SQLModel, table=True):
    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    speech_id: str = Field(foreign_key="speech.id")
    user_id: str = Field(foreign_key="user.id")
    is_public: bool = True
    career_tag: Optional[str] = None
    topic_tag: Optional[str] = None
    like_count: int = 0
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class Like(SQLModel, table=True):
    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    post_id: str = Field(foreign_key="communitypost.id")
    user_id: str = Field(foreign_key="user.id")
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class MentorConnection(SQLModel, table=True):
    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    requester_id: str = Field(foreign_key="user.id")
    mentor_id: str = Field(foreign_key="user.id")
    speech_id: str = Field(foreign_key="speech.id")
    status: str = "pending"
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class ChatMessage(SQLModel, table=True):
    id: str = Field(default_factory=lambda: str(uuid4()), primary_key=True)
    session_hash: str = Field(index=True)   # sha256(speech_id)[:16]
    speech_id: Optional[str] = Field(default=None, foreign_key="speech.id")
    role: str                               # "user" | "model"
    phase: str = "preptalk"                 # "preptalk" | "activetalk" | "talksummary"
    content: str
    summary: str = ""                       # 3-5 word label generated by Gemini
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# ─────────────────────────────────────────────────────────────────────────────
# Heard v2 — auth profiles, channels, threads, training sessions, DMs.
#
# `Profile.id` == the Supabase Auth user id (== local `User.id`). We keep the
# legacy `User` table for the old speech/feed features; `Profile` holds the
# public-facing identity (display_name, username, avatar, bio) used by the new
# channel / leaderboard / DM flows. Table names are set explicitly so the ORM
# (dev SQLite) and the Supabase Postgres migration stay in sync.
# ─────────────────────────────────────────────────────────────────────────────

# Thread types
THREAD_PRE_TRAINING = "PRE_TRAINING"
THREAD_POST_TRAINING = "POST_TRAINING"

# Session statuses
SESSION_ACTIVE = "ACTIVE"
SESSION_PROCESSING = "PROCESSING"
SESSION_COMPLETED = "COMPLETED"
SESSION_FAILED = "FAILED"


class Profile(SQLModel, table=True):
    __tablename__ = "profiles"

    id: str = Field(primary_key=True)  # == Supabase auth user id
    display_name: Optional[str] = None
    username: Optional[str] = Field(default=None, index=True, unique=True)
    avatar_url: Optional[str] = None
    bio: Optional[str] = None
    is_private: bool = False
    # Stable per-user Backboard coach assistant (longitudinal memory anchor).
    backboard_assistant_id: Optional[str] = None
    created_at: str = Field(default_factory=_now_iso)
    updated_at: str = Field(default_factory=_now_iso)


class Channel(SQLModel, table=True):
    __tablename__ = "channels"

    id: str = Field(default_factory=_uuid, primary_key=True)
    slug: str = Field(unique=True, index=True)
    name: str
    description: str = ""
    created_at: str = Field(default_factory=_now_iso)


class ChannelMembership(SQLModel, table=True):
    __tablename__ = "user_channel_memberships"
    __table_args__ = (
        UniqueConstraint("user_id", "channel_id", name="uq_membership_user_channel"),
    )

    id: str = Field(default_factory=_uuid, primary_key=True)
    user_id: str = Field(index=True, foreign_key="profiles.id")
    channel_id: str = Field(index=True, foreign_key="channels.id")
    joined_at: str = Field(default_factory=_now_iso)


class ChatThread(SQLModel, table=True):
    __tablename__ = "chat_threads"
    __table_args__ = (
        Index("ix_thread_user_channel_updated", "user_id", "channel_id", "updated_at"),
    )

    id: str = Field(default_factory=_uuid, primary_key=True)
    user_id: str = Field(index=True, foreign_key="profiles.id")
    channel_id: str = Field(index=True, foreign_key="channels.id")
    thread_type: str = THREAD_PRE_TRAINING  # PRE_TRAINING | POST_TRAINING
    session_id: Optional[str] = Field(default=None, index=True)
    title: str = ""
    # Backboard thread id (vendor conversation state), reused across messages.
    backboard_thread_id: Optional[str] = None
    created_at: str = Field(default_factory=_now_iso)
    updated_at: str = Field(default_factory=_now_iso)


class ThreadMessage(SQLModel, table=True):
    __tablename__ = "chat_messages"
    __table_args__ = (
        Index("ix_message_thread_created", "thread_id", "created_at"),
    )

    id: str = Field(default_factory=_uuid, primary_key=True)
    thread_id: str = Field(index=True, foreign_key="chat_threads.id")
    sender_type: str  # "user" | "assistant" | "system" | "transcript"
    content: str
    message_metadata: dict = Field(default_factory=dict, sa_column=Column("metadata", JSON))
    created_at: str = Field(default_factory=_now_iso)


class TrainingSession(SQLModel, table=True):
    __tablename__ = "training_sessions"
    __table_args__ = (
        Index("ix_session_user_channel_created", "user_id", "channel_id", "created_at"),
    )

    id: str = Field(default_factory=_uuid, primary_key=True)
    user_id: str = Field(index=True, foreign_key="profiles.id")
    channel_id: str = Field(index=True, foreign_key="channels.id")
    title: str = ""
    status: str = SESSION_ACTIVE  # ACTIVE | PROCESSING | COMPLETED | FAILED
    started_at: str = Field(default_factory=_now_iso)
    ended_at: Optional[str] = None
    duration_seconds: float = 0.0
    total_words: int = 0
    created_at: str = Field(default_factory=_now_iso)


class TranscriptSegment(SQLModel, table=True):
    __tablename__ = "transcript_segments"
    __table_args__ = (
        UniqueConstraint("session_id", "segment_index", name="uq_segment_session_index"),
    )

    id: str = Field(default_factory=_uuid, primary_key=True)
    session_id: str = Field(index=True, foreign_key="training_sessions.id")
    segment_index: int
    transcript: str = ""
    start_seconds: float = 0.0
    end_seconds: float = 0.0
    duration_seconds: float = 0.0
    word_count: int = 0
    audio_metrics: dict = Field(default_factory=dict, sa_column=Column(JSON))
    created_at: str = Field(default_factory=_now_iso)


class SessionFeedback(SQLModel, table=True):
    __tablename__ = "session_feedback"

    id: str = Field(default_factory=_uuid, primary_key=True)
    session_id: str = Field(unique=True, index=True, foreign_key="training_sessions.id")
    # Six communication dimensions (volume nullable when no audio metrics).
    clarity_score: Optional[float] = None
    conciseness_score: Optional[float] = None
    pace_score: Optional[float] = None
    volume_score: Optional[float] = None      # null when no audio metrics supplied
    confidence_score: Optional[float] = None
    structure_score: Optional[float] = None
    overall_score: Optional[float] = None
    # Which dimensions could not be scored (e.g. "volume" without audio).
    unavailable_dimensions: list = Field(default_factory=list, sa_column=Column(JSON))
    # Headline deterministic numbers (kept as columns for cheap querying).
    filler_count: int = 0
    filler_rate: float = 0.0                  # fillers per 100 words
    average_wpm: float = 0.0
    volume_consistency: Optional[float] = None
    # Legacy-friendly flat lists.
    strengths: list = Field(default_factory=list, sa_column=Column(JSON))
    improvements: list = Field(default_factory=list, sa_column=Column(JSON))
    summary: str = ""
    detailed_feedback: dict = Field(default_factory=dict, sa_column=Column(JSON))
    # Rich longitudinal analysis (evidence packet + AI structured output).
    metrics_summary: dict = Field(default_factory=dict, sa_column=Column(JSON))
    longitudinal_analysis: dict = Field(default_factory=dict, sa_column=Column(JSON))
    strongest_moments: list = Field(default_factory=list, sa_column=Column(JSON))
    priority_moments: list = Field(default_factory=list, sa_column=Column(JSON))
    persistent_patterns: list = Field(default_factory=list, sa_column=Column(JSON))
    new_patterns: list = Field(default_factory=list, sa_column=Column(JSON))
    stable_strengths: list = Field(default_factory=list, sa_column=Column(JSON))
    next_session_goals: list = Field(default_factory=list, sa_column=Column(JSON))
    metrics_interpretation: dict = Field(default_factory=dict, sa_column=Column(JSON))
    vocal_variety: dict = Field(default_factory=dict, sa_column=Column(JSON))
    created_at: str = Field(default_factory=_now_iso)


class DMConversation(SQLModel, table=True):
    __tablename__ = "dm_conversations"

    id: str = Field(default_factory=_uuid, primary_key=True)
    # Deterministic key for a 1:1 pair — "min(uid)|max(uid)" — enforces no dupes.
    pair_key: Optional[str] = Field(default=None, unique=True, index=True)
    created_at: str = Field(default_factory=_now_iso)
    updated_at: str = Field(default_factory=_now_iso)


class DMMember(SQLModel, table=True):
    __tablename__ = "dm_members"
    __table_args__ = (
        UniqueConstraint("conversation_id", "user_id", name="uq_dm_member"),
    )

    id: str = Field(default_factory=_uuid, primary_key=True)
    conversation_id: str = Field(index=True, foreign_key="dm_conversations.id")
    user_id: str = Field(index=True, foreign_key="profiles.id")


class DMMessage(SQLModel, table=True):
    __tablename__ = "dm_messages"
    __table_args__ = (
        Index("ix_dm_message_conv_created", "conversation_id", "created_at"),
    )

    id: str = Field(default_factory=_uuid, primary_key=True)
    conversation_id: str = Field(index=True, foreign_key="dm_conversations.id")
    sender_id: str = Field(index=True, foreign_key="profiles.id")
    content: str
    created_at: str = Field(default_factory=_now_iso)
    read_at: Optional[str] = None


class UserChannelPerformanceProfile(SQLModel, table=True):
    """Compact, channel-specific longitudinal summary derived from sessions.

    NOT a replacement for raw session history — a fast-to-load rollup that
    pre-/post-training AI calls use to understand the user's trajectory. Updated
    after each completed session.
    """
    __tablename__ = "user_channel_performance_profiles"
    __table_args__ = (
        UniqueConstraint("user_id", "channel_id", name="uq_perf_user_channel"),
    )

    id: str = Field(default_factory=_uuid, primary_key=True)
    user_id: str = Field(index=True, foreign_key="profiles.id")
    channel_id: str = Field(index=True, foreign_key="channels.id")
    completed_sessions: int = 0
    baseline_score: Optional[float] = None
    recent_score: Optional[float] = None
    improvement_percent: Optional[float] = None
    dimension_trends: dict = Field(default_factory=dict, sa_column=Column(JSON))
    recurring_strengths: list = Field(default_factory=list, sa_column=Column(JSON))
    recurring_weaknesses: list = Field(default_factory=list, sa_column=Column(JSON))
    recent_patterns: list = Field(default_factory=list, sa_column=Column(JSON))
    current_training_goals: list = Field(default_factory=list, sa_column=Column(JSON))
    updated_at: str = Field(default_factory=_now_iso)
